# docker-compose.yml
version: "3"
services:
  app:
    container_name: node_docker_demo
    build: .
    volumes:
      - ./server:/usr/src/app/server
    command: npm start
    restart: always
    ports:
      - "8080:8080"
    external_links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - '27018:27017'